import React, { useState } from 'react';
import { History as HistoryIcon, Eye } from 'lucide-react';
import { useProduct } from '../context/ProductContext';
import Barcode from 'react-barcode';
import QRCodeModal from '../components/QRCodeModal';

const ProductHistory = ({ searchTerm = '' }) => {
    const { products } = useProduct();
    const [isQRModalOpen, setIsQRModalOpen] = useState(false);
    const [selectedProduct, setSelectedProduct] = useState(null);

    // Filter products that have QR Generated (Column F is not null)
    const filteredProducts = products
        .filter(product => product.qrGenerated) // Only show items where Column F has data
        .filter(product =>
            product.productName?.toLowerCase().includes(searchTerm.toLowerCase()) ||
            product.sn?.toLowerCase().includes(searchTerm.toLowerCase()) ||
            product.sku?.toLowerCase().includes(searchTerm.toLowerCase()) ||
            product.generatedBy?.toLowerCase().includes(searchTerm.toLowerCase())
        )
        .sort((a, b) => new Date(b.qrGeneratedDate || 0) - new Date(a.qrGeneratedDate || 0));

    const handleShowQR = (product) => {
        setSelectedProduct(product);
        setIsQRModalOpen(true);
    };

    return (
        <div className="flex flex-col h-full overflow-hidden">
            {/* Search toolbar removed - controlled by parent */}

            <div className="flex justify-end px-6 py-2 text-sm text-slate-500">
                {filteredProducts.length} items
            </div>

            {/* Table Container - Scrollable area */}
            <div className="flex-1 overflow-auto px-4 pb-6 md:px-6">
                {/* Hidden Assets for PDF Generation */}
                <div className="hidden">
                    {products.map(p => (
                        <div key={`assets-${p.id}`} id={`barcode-hidden-${p.id}`}>
                            <Barcode
                                value={p.model || p.sku || p.sn}
                                format="CODE128"
                                width={2}
                                height={100}
                                displayValue={false}
                            />
                        </div>
                    ))}
                </div>

                {/* Desktop Table View */}
                <div className="hidden md:block bg-white rounded-xl shadow-sm border border-slate-200">
                    <table className="w-full text-left text-sm border-separate border-spacing-0">
                        <thead className="text-slate-700 font-semibold">
                            <tr>
                                <th className="px-4 py-3 bg-slate-50 border-b border-slate-200 first:rounded-tl-xl">Serial No</th>
                                <th className="px-4 py-3 bg-slate-50 border-b border-slate-200">Category</th>
                                <th className="px-4 py-3 bg-slate-50 border-b border-slate-200">Item Name</th>
                                <th className="px-4 py-3 bg-slate-50 border-b border-slate-200">Item Code</th>
                                <th className="px-4 py-3 text-center bg-slate-50 border-b border-slate-200">Qty</th>
                                <th className="px-4 py-3 bg-slate-50 border-b border-slate-200">QR Generate Date</th>
                                <th className="px-4 py-3 bg-slate-50 border-b border-slate-200">Generated By</th>
                                <th className="px-4 py-3 text-center bg-slate-50 border-b border-slate-200 last:rounded-tr-xl">Action</th>
                            </tr>
                        </thead>
                        <tbody className="divide-y divide-slate-100">
                            {filteredProducts.length > 0 ? (
                                filteredProducts.map((product) => (
                                    <tr key={product.id} className="hover:bg-slate-50 transition-colors">
                                        <td className="px-4 py-3 font-semibold text-light-blue-700">{product.sn}</td>
                                        <td className="px-4 py-3 text-slate-600">{product.category}</td>
                                        <td className="px-4 py-3 text-slate-900 font-medium">{product.productName}</td>
                                        <td className="px-4 py-3 text-slate-600 text-[10px] uppercase tracking-wider">{product.sku}</td>
                                        <td className="px-4 py-3 text-center">
                                            <span className="px-2 py-1 rounded-full bg-slate-100 text-slate-600 text-xs font-bold border border-slate-200">
                                                {product.batchCount || 1}
                                            </span>
                                        </td>
                                        <td className="px-4 py-3 text-slate-600 text-xs">
                                            {product.qrGeneratedDate || '-'}
                                        </td>
                                        <td className="px-4 py-3 text-slate-600 text-sm font-medium">
                                            {product.generatedBy || '-'}
                                        </td>
                                        <td className="px-4 py-3 text-center">
                                            <button
                                                onClick={() => handleShowQR(product)}
                                                className="p-1.5 text-light-blue-600 hover:bg-light-blue-50 rounded-lg transition-colors border border-transparent hover:border-light-blue-100"
                                                title="View Barcode"
                                            >
                                                <Eye size={18} />
                                            </button>
                                        </td>
                                    </tr>
                                ))
                            ) : (
                                <tr>
                                    <td colSpan="8" className="px-4 py-20 text-center">
                                        <div className="flex flex-col items-center justify-center text-slate-400">
                                            <HistoryIcon size={48} className="mb-4 opacity-20" />
                                            <p className="text-lg font-medium">No results found</p>
                                            <p className="text-sm mt-1">Items will appear here once QR codes are generated</p>
                                        </div>
                                    </td>
                                </tr>
                            )}
                        </tbody>
                    </table>
                </div>

                {/* Mobile Card View */}
                <div className="md:hidden space-y-3">
                    {filteredProducts.length > 0 ? (
                        filteredProducts.map((product) => (
                            <div key={product.id} className="bg-white rounded-xl p-4 shadow-sm border border-slate-100">
                                <div className="flex justify-between items-start mb-2">
                                    <div>
                                        <h3 className="font-semibold text-slate-900 line-clamp-1">{product.productName}</h3>
                                        <p className="text-xs text-slate-500 uppercase tracking-wider">{product.sku}</p>
                                    </div>
                                    <span className="text-[10px] font-mono bg-slate-100 text-slate-500 px-1.5 py-0.5 rounded ml-2 whitespace-nowrap">
                                        {product.sn}
                                    </span>
                                </div>

                                <div className="grid grid-cols-2 gap-2 text-xs text-slate-500 mb-3">
                                    <div>
                                        <span className="text-slate-400">Category:</span> {product.category}
                                    </div>
                                    <div>
                                        <span className="text-slate-400">Qty:</span> {product.batchCount || 1}
                                    </div>
                                    <div>
                                        <span className="text-slate-400">Date:</span> {product.qrGeneratedDate || '-'}
                                    </div>
                                    <div>
                                        <span className="text-slate-400">By:</span> {product.generatedBy || '-'}
                                    </div>
                                </div>

                                <div className="flex items-center justify-end border-t border-slate-50 pt-3 mt-1">
                                    <button
                                        onClick={() => handleShowQR(product)}
                                        className="flex items-center gap-1.5 text-xs font-medium text-light-blue-600 bg-light-blue-50 px-3 py-1.5 rounded-lg active:bg-light-blue-100"
                                    >
                                        <Eye size={14} />
                                        View
                                    </button>
                                </div>
                            </div>
                        ))
                    ) : (
                        <div className="text-center py-12 text-slate-400">
                            <HistoryIcon size={48} className="mx-auto mb-3 opacity-20" />
                            <p>No history found</p>
                        </div>
                    )}
                </div>
            </div>

            <QRCodeModal
                isOpen={isQRModalOpen}
                onClose={() => setIsQRModalOpen(false)}
                product={selectedProduct}
            />
        </div>
    );
};

export default ProductHistory;
